### ISSUE TITLE
No change notification for o.fd.UDisks2.Filesystem.Size anymore

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/udisks#1008]
I think we lost the property change notifications with #949, no?

**Comment by tbzatek** [comment]
Ah right, it was changed to be on demand only. I knew why I wasn't convinced to push this change to stable...

Hmm, hmm, the problem was an endless uevent storm so we had to decouple that. Caused by certain filesystems that generate extra uevent once you retrieve the filesystem size. And we simply can't refresh the fs size as a result of a uvent, no matter how delayed the refresh would be. The change to the behaviour was a compromise between changing the API, deprecation and introducing a getter method.

If it's suitable for your use case, can you just use the built-in `org.freedesktop.DBus.Properties.Get()` method to trigger the refresh after you make any modification to the filesystem or on a first object retrieval? I suppose this value wouldn't change often.

**Comment by mvollmer** [comment]
I think we really should fix dumpe2fs or stop using it.  Here is a potential fix: https://github.com/tytso/e2fsprogs/pull/122

To stop using it, libblockdev could use libext2fs directly instead of spawning dumpe2fs.  That's probably a good idea in general. I'll have a stab at that.

**Comment by mvollmer** [comment]
Here is my first toy program, looks promising:

```
#include <stdio.h>
#include <ext2fs.h>
#include <e2p.h>

void
main (int argc, char **argv)
{
  errcode_t retval;
  ext2_filsys fs;

  retval = ext2fs_open (argv[1],
                        EXT2_FLAG_JOURNAL_DEV_OK | EXT2_FLAG_SOFTSUPP_FEATURES |
                        EXT2_FLAG_64BITS | EXT2_FLAG_THREADS | EXT2_FLAG_SUPER_ONLY |
                        EXT2_FLAG_IGNORE_CSUM_ERRORS,
                        0, // use_superblock
                        0, // use_blocksize
                        unix_io_manager,
                        &fs);

  if (retval) {
    printf ("OPEN %d\n", retval);
    exit (1);
  }

  printf ("%llu\n", ((unsigned long long) ext2fs_blocks_count(fs->super)) * EXT2_BLOCK_SIZE(fs->super));
}
```

**Comment by tbzatek** [comment]
> I think we really should fix dumpe2fs or stop using it. Here is a potential fix: [tytso/e2fsprogs#122](https://github.com/tytso/e2fsprogs/pull/122)

Nice!

One other major reason for making the property value retrieval on demand was to relieve I/O traffic. In practice, all other properties were retrieved from the (cached) udev database. In small systems this was not a big issue, the problem was daemon startup and first enumeration in case of large number of block devices.

We've had bugreports about the daemon not starting up in a reasonable time (30+ sec.) when autostarted from a first D-Bus call, resulting in the `gvfs udisks2` volume monitor bailing out, falling back to local GIO unix monitoring. This happened on a system with rotational disks during higher load upon system startup.

**Comment by vojtechtrefny** [comment]
Related: libblkid now has two now filesystem two properties/tags: `FSSIZE` and [`FSLASTBLOCK`](https://github.com/util-linux/util-linux/pull/1665) (not yet released) which we potentially could use for getting filesystem size, it will be also likely available in udev (which just calls blkid) so we could get these "for free" without calling libblockdev.

**Comment by mvollmer** [comment]
> libblkid now has two now filesystem two properties/tags: FSSIZE and https://github.com/util-linux/util-linux/pull/1665

Nice!

**Comment by tbzatek** [comment]
ping @mvollmer - any chance to test #1042 please?
