### ISSUE TITLE
any updates for ntfs3 in linux 6.0?

### ISSUE THREAD

**Issue by Firestar-Reimu** [storaged-project/udisks#1028]
ntfs3 has updated in linux 6.0, will there be any updates for it?

PS: it still do not provide `windows-names`

**Comment by tbzatek** [comment]
Feel free to post a patch!

**Comment by Firestar-Reimu** [comment]
On Archlinux with kernel linux 6.0, still happens: `Filesystem type ntfs3,ntfs not configured in kernel.` error in Dolphin

**Comment by tbzatek** [comment]
Please wait for the final UDisks 2.10.0 release bearing the proper fix. In the meantime, feel free to follow up with your distribution.

I'm going to close this ticket now, you may still report issues found in the current git version - testing is appreciated.

**Comment by mbiebl** [comment]
> Please wait for the final UDisks 2.10.0 release bearing the proper fix. In the meantime, feel free to follow up with your distribution.

hi @tbzatek do you have an ETA for the 2.10.0 release?
I'm asking, because the freeze for the next debian release (bookworm) is coming closer and I wonder if we will release with 2.9.4 or 2.9.5/2.10.0?

**Comment by tbzatek** [comment]
> hi @tbzatek do you have an ETA for the 2.10.0 release? I'm asking, because the freeze for the next debian release (bookworm) is coming closer and I wonder if we will release with 2.9.4 or 2.9.5/2.10.0?

I wish I could give you any date but there's any at the moment. While `udisks` development is mostly done for the upcoming release, we're still breaking `libblockdev` API for the major 3.0 release. There's still some work to be done and I'm not happy either that it takes such long time. It also doesn't make sense to release any snapshots at the moment since we know the API will still change (and intentionally don't want any distros to ship that). Lastly, there were so many changes that backporting selective features is mostly out of question and since we don't have CI setup for the stable branches, no guarantees of quality either.

**Comment by Firestar-Reimu** [comment]
The `Linux 6.2-rc7` release today mark that 6.2 will be stable soon, hoping that udisks and libblockdev will release maybe before March, with the release of Linux 6.2?

**Comment by tbzatek** [comment]
> The `Linux 6.2-rc7` release today mark that 6.2 will be stable soon, hoping that udisks and libblockdev will release maybe before March, with the release of Linux 6.2?

Kernel version doesn't matter anymore, we made `ntfs3` mount option definitions compatible across all released kernel versions that ever carried `ntfs3`.
