### ISSUE TITLE
udisks daemon Timeout was reached

### ISSUE THREAD

**Issue by jtroeth1** [storaged-project/udisks#1060]
Hi There, 

We have an automated system that does some copying to a usb thumbdrive. The process mounts the device using udisksctl mount -b <device>, copies using rsync, then unmounts with udisksctl unmount -b <device>.

We have have been seeing an issue where the udisks daemon hangs on the unmount command (or prior) and on return of the unmount command we get _"Error connecting to the udisks daemon: Timeout was reached"_.

We have been also been logging using udisksctl monitor to see if we could find anything, but this too, just stops logging when the daemon hangs for eg after 05:26:05:

Feb 05 05:12:42 OS02-22 udisksd[922]: Mounted /dev/sdb1 at <path> on behalf of uid 1000
Feb 05 05:25:37 OS02-22 udisksd[922]: Cleaning up mount point <path> (device 8:17 is not mounted)
Feb 05 05:26:05 OS02-22 udisksd[922]: Unmounted /dev/sdb1 on behalf of uid 1000
Feb 05 05:26:05 OS02-22 udisksd[922]: Mounted /dev/sdb1 at <path> on behalf of uid 1000

I ran a test script that mounted and unmounted a device repeatedly, and saw no issue. During the unmount, it is likely that the device is still being flushed, but this shouldn't be an issue as it usually unmounts once this is complete.

Possibly related? - we also see this message in the journal:
Feb 05 05:26:55 OS02-22 NetworkManager[841]: <warn>  [1675574815.1961] modem-manager: error creating ModemManager client: Timeout was reached

I haven't been able to find anything on the internet about it and it is causing a major hassle for us. Has anyone seen this issue? and how can I debug this further?

Other info:
This process is performed roughly 20 times a day.
We are using Fedora 31, kernel version 5.3.7-301.fc31.x86_64
udisks version 2.8.4
The filesystem being mounted is exfat

Thanks

**Comment by tbzatek** [comment]
> We are using Fedora 31, kernel version 5.3.7-301.fc31.x86_64
> The filesystem being mounted is exfat

This means you're likely using the `fuse` module, right? There have been various issues and the native kernel driver should work better.

> udisks version 2.8.4

There was really a lot of changes up to the 2.9.4 latest release and equally lot of change in the current git master, becoming 2.10.0 release soon. Any chance to retest this?

> Feb 05 05:26:55 OS02-22 NetworkManager[841]: [1675574815.1961] modem-manager: error creating ModemManager client: Timeout was reached

Interesting, this indicates issues with the system bus. I've seen similar issue on recent rawhide but it got magically fixed by some update.

> how can I debug this further?

If you attach `gdb` to a running `udisksd` process and grab the stacktrace with all threads at the point the daemon is frozen, it might show us what's happening.
https://fedoraproject.org/wiki/StackTraces

**Comment by tbzatek** [comment]
No response for over a year, closing.
