### ISSUE TITLE
Message recipient disconnected from message bus without replying

### ISSUE THREAD

**Issue by EmJotGeh** [storaged-project/udisks#1109]
https://github.com/util-linux/util-linux/issues/2267

**Comment by t-8ch** [comment]
This is most likely a bug within util-linux.

**Comment by tbzatek** [comment]
Yup, thanks for reporting anyway!

The `util-linux-2.39` release incl. some -rc versions as available in rawhide were daily tested in our CI, however only on the master branch that has changed a lot since the udisks-2.9.4 release and no longer contains the `ntfs3,ntfs` fstype hack. So it got some coverage and the only difference found was this one https://github.com/storaged-project/udisks/pull/1099/commits/bf1dc246ac266fbc5f7512639e870df5c03ddb75
