### ISSUE TITLE
udisksd crashes unless all libblockdev plugins are available

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/udisks#1142]
Hi,

in previous udisks releases (< 2.10) I made mdraid and crypto plugins optional in Debian, i.e. the udisks2 package did not depend on libblockdev-mdraid2 and libblockdev-crypto2, but only recommended those packages.

With udisks 2.10, a missing libblockdev plugin results in a crash, see e.g.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040793

As a workaround, I changed those dependencies to hard Depends
https://salsa.debian.org/utopia-team/udisks2/-/commit/eb130cfbb5ec1d51b8522625c6354cd151badeb3

Is this behaviour expected?
Can missing plugins be handled more gracefully as in older releases or is this a deliberate decision?

**Comment by vojtechtrefny** [comment]
This was an intentional change by @tbzatek, see https://github.com/storaged-project/udisks/commit/ff5fddb16a97d8f1b8475a219566c2ee95f3c349 
The mdraid and crypto plugins were never optional -- only optional plugins are those used by the udisks module (LVM, btrfs...). Yes, udisks can work without the plugins, but only if you don't have any LUKS or MD device (and with 2.10 also NVMe drive). When a LUKS/MD/NVMe device shows up, we'll try to use the libblockdev functions to gather information about it and udisks will crash anyway. I understand people don't like dependencies and this is bit controversial decision, but I don't think it make sense in this case to force these to be optional. We had some people asking to make MD and/or LUKS support optional, but it's not possible to make these into separate modules without an API change.

**Comment by mbiebl** [comment]
Ok, thanks for the clarification. I'll close this issue as wont-fix then and keep the hard depends downstream. Will see if users are going to complain or not

**Comment by vojtechtrefny** [comment]
Note that having `mdadm` is not required. Only `libblockdev-mdraid` is needed. The libblockdev plugin will load without it.

**Comment by mbiebl** [comment]
It's correct, that the libblockdev-mdraid package in Debian has a hard dependency on mdadm, for the simple reason, that the plugin calls out to the mdadm binary. 
I haven't tested if the plugin handles it gracefully, if the binary is missing, but imho it would be the same issue as what ff5fddb tried to fix, just that the issue has been pushed down one layer down.

**Comment by mbiebl** [comment]
Here is the current set of package including their dependencies:
https://salsa.debian.org/utopia-team/libblockdev/-/blob/debian/sid/debian/control#L95

As you can see
- libblockdev-btrfs3 depends on btrfs-progs
-  libblockdev-dm3 on dmsetup
-  libblockdev-lvm3 on lvm2
- libblockdev-mdraid3 on mdam
-  libblockdev-mpath3 on multipath-tools
- libblockdev-nvdimm3 on ndctl
- libblockdev-part3 on fdisk

@vojtechtrefny if I understand you correctly, you'd prefer if those dependencies were dropped or demoted to something like Recommends?

**Comment by vojtechtrefny** [comment]
I'd prefer to keep the dependencies. The question about requiring the runtime dependencies is mostly theoretical -- the note I made I was aiming mostly at people that really hate having mdadm in their system and want to get rid of it. Libblockdev can work without runtime dependencies, it has a API to check for runtime dependencies availability and all functions should return a meaningful error when called with a missing runtime dependency (= we will tell you *mdadm is missing* not just crash or return some random *no such file or directory* error) and for some plugins it make sense to not require all dependencies, because some of them are needed only for some subset of the plugin functionality. Filesystem plugin is a good example -- you don't need *xfsprogs* to work with ext4 so requiring all runtime dependencies for that plugin doesn't really make sense. But for the MD plugin, there is just a handful of helper functions that will work without mdadm so it makes sense to have it as a "hard" dependency.

**Comment by vojtechtrefny** [comment]
>     * libblockdev-part3 on fdisk

This one is actually not needed -- we need only the library, not the command line tools.

**Comment by mbiebl** [comment]
And we have the first downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040908

**Comment by mbiebl** [comment]
> > ```
> > * libblockdev-part3 on fdisk
> > ```
> 
> This one is actually not needed -- we need only the library, not the command line tools.

Thanks, will drop that dependency!

**Comment by seb128** [comment]
For the record I reverted ff5fddb in Ubuntu for now to avoid the extra depends (it will require extra packages to be promoted to our main component at minimum which usually takes some time, also it's unclear if we want to pull mdadm on the desktop installation)
