### ISSUE TITLE
Newbie question: How to build udisks with a development version of libblockdev?

### ISSUE THREAD

**Issue by squimrel** [storaged-project/udisks#309]
What's the recommended way to build udisks with a development version of libblockdev that preferably isn't installed on the system?

**Comment by vpodzime** [comment]
> What's the recommended way to build udisks with a development version of libblockdev that preferably isn't installed on the system?

I have no real tips other than adding proper ``-I`` and ``-L`` options so that the header files and libraries are found when compiling and linking. Note that *libblockdev* creates an ``include`` directory when building which could be used for purposes like this. Then you need to run the daemon with ``LD_LIBRARY_PATH`` including the ``.libs`` directories from *libblockdev*.

**Comment by squimrel** [comment]
So it has to be done manually.
