### ISSUE TITLE
Missing NULL checks, goto, checks on right side

### ISSUE THREAD

**Issue by jonnygrant** [storaged-project/udisks#463]
https://github.com/storaged-project/udisks/blob/master/udisks/udisksclient.c

Missing NULL checks, goto, checks on right side

eg

if ((id_type[n].version == NULL && strlen (version) == 0))

for (n = 0; known_partition_table_types[n].type != NULL; n++)

The whole file has lots of these problems. Can they all be fixed? Every function has missed NULL checks, eg udisks_client_get_partition_table_type_for_display
Combined if, should have each condition in parenthesis 

Probably the whole module has these issues.  Can regular static analysis be introduced as part of the build?

**Comment by tbzatek** [comment]
> https://github.com/storaged-project/udisks/blob/master/udisks/udisksclient.c
> 
> Missing NULL checks, goto, checks on right side

Can you post example of a missing NULL check?
What's wrong with goto? Is it missing somewhere?
And with checks on right side, do you mean construction like `NULL == object` ?

> 
> eg
> 
> `if ((id_type[n].version == NULL && strlen (version) == 0))`

Yeah, that's just one occurrence where the double parenthesis is unnecessary.

> `for (n = 0; known_partition_table_types[n].type != NULL; n++)`

What's wrong with this one?

> The whole file has lots of these problems. Can they all be fixed? Every function has missed NULL checks, eg `udisks_client_get_partition_table_type_for_display`

This function seems perfectly clean to me. What NULL checks are missing there?

> Combined if, should have each condition in parenthesis

Not in C, on the contrary, this will lead to excessive parenthesis and less readable code.

> Probably the whole module has these issues. Can regular static analysis be introduced as part of the build?

We already run the `csmock` task along with package build and the test suite.

**Comment by jonnygrant** [comment]
Wonder if csmock is run with all combinations of unexpected parameters? Or only test expected success cases.

If you're asking me why goto is bad in programming, I can only suggest googling it, or reading a programming book, not here to teqach C programming. if() replaced goto since 1980s.

The code is in out of date C style, look how the variables are not declared in scope of the for loop.
same in this function udisks_partition_type_info_new. it should be as follows, we're not in the 1980s anymore.
UDisksPartitionTypeInfo *ret= g_slice_new0 (UDisksPartitionTypeInfo);

yes, as you say, NULL == object

Most of the functions don't check pointers are valid before de-referencing them, eg udisks_client_get_property


initable_init (GInitable     *initable,
               GCancellable  *cancellable,
               GError       **error)
why not start by checking arguments are valid parameter values, ie non-NULL?

**Comment by tbzatek** [comment]
> Wonder if csmock is run with all combinations of unexpected parameters? Or only test expected success cases.

Part of the tests include static analysis which should consider all branches. It's not a fuzzer though that might reveal odd behaviour in certain cases. Feel free to run one and open separate tickets if anything is not working properly.

> If you're asking me why goto is bad in programming, I can only suggest googling it, or reading a programming book, not here to teqach C programming. if() replaced goto since 1980s.

I'm sorry, this is not an argument, just a one-side opinion. Feel free to reach linux kernel developers or the Gnome community for further explanation about `goto` usage. This topic of course has been discussed many times in the past.

> The code is in out of date C style, look how the variables are not declared in scope of the for loop.
> same in this function udisks_partition_type_info_new. it should be as follows, we're not in the 1980s anymore.

Please read through https://developer.gnome.org/programming-guidelines/stable/index.html.en#general-guidelines

(and notice the usage of `goto` in the examples)

We're mostly following Gnome guidelines in `udisks`, of course there are snippets of code that could use minor cleanup.

> Most of the functions don't check pointers are valid before de-referencing them, eg udisks_client_get_property

Many static functions don't need explicit value validity checking as the input is more or less predictable within the single file - and sometimes guaranteed by GObject calling conventions. For public symbols more checks would be desirable.

Please also note that many functions we pass the values in handle _NULL_ or invalid values gracefully. These specifics can be found in gtk-doc-like documentation that often includes annotations for data type input/output range, memory ownership and conversion hints (gobject-introspection).

> 
> initable_init (GInitable *initable,
> GCancellable *cancellable,
> GError **error)
> why not start by checking arguments are valid parameter values, ie non-NULL?

See above, e.g. for error reporting the convention is often `(nullable)` - see https://wiki.gnome.org/Projects/GObjectIntrospection/Annotations/#Nullable_parameters

----

Okay, this starts looking like a flame. So while I appreciate taking your time to describe the principles of modern C code style by the book, we already follow our (or, to be precise, inherited) code style that has proven to be adequate, working and transparent for years. This applies not only to code style, but also calling conventions, API design, memory management, commonly used annotations and doc strings, etc. 

As a benefit this brings advantages to the broader Gnome community contributors as we're all used to the same style. This saves time during code review and often prevents logical errors that would again take time to debug (memory management, object reference counting, etc.).

You're always welcome to send patches for particular cases where invalid input may cause misbehaviour or in case of badly checked result, etc. However I do not think this discussion is constructive and I don't see any major issue that should be fixed here. If you feel our code style should be changed, please reach out to the authors of the code style guidelines linked above so that all of us could benefit from the improvements. Closing for now.

**Comment by jonnygrant** [comment]
Many thanks for your reply. Gambling on NULL ptr safety is a risk, especially when new code is added. I'm sure you already know that compilers would optimise out any unrequired NULL checks.

The link you kindly shared didn't mention goto, but it sounds like perhaps the problem is udisks following an out-of-date programming style from 1980s C. I appreciate that is not your decision, although it would be worth raising this and Gnome moving with the times. I'll leave that with you.

**Comment by vpodzime** [comment]
> The link you kindly shared didn't mention goto, but it sounds like perhaps the problem is udisks following an out-of-date programming style from 1980s C. I appreciate that is not your decision, although it would be worth raising this and Gnome moving with the times. I'll leave that with you.

We are just not *the cool let's-rewrite-everything-ideally-in-Rust kids* here.
