### ISSUE TITLE
Add windows_names as a default mount option for ntfs-3g

### ISSUE THREAD

**Issue by A-Shahbazi** [storaged-project/udisks#620]
I think it's a good idea to add 'windows_names' as a default mount option for ntfs-3g. The main reason of being able to use ntfs on linux is interoperability with windows operating system. However, I would personally run into problems when copied a bunch of files from my ext4 filesystem to my ntfs flashdrive and because of the naming convention had to go through irresponsive filesystem and fixing it with chkdsk.exe everytime on windows OS. This led to some files being moved to a garbage folder with arbitrary namings which took even further effort to find what is what in that folder to find my files.

**Comment by A-Shahbazi** [comment]
BTW, I can make a PR if this sounds good to the maintainer.

**Comment by tbzatek** [comment]
> BTW, I can make a PR if this sounds good to the maintainer.

Yes, please open a PR with intended changes. Thanks!

Btw. is this option available in earlier ntfs-3g releases? If not, would it fail mounting or simply gets ignored?

**Comment by dwlehman** [comment]
I'm curious: If this is the main use case for mounting ntfs in linux, why not make it the default in ntfs-3g?

**Comment by A-Shahbazi** [comment]
> I'm curious: If this is the main use case for mounting ntfs in linux, why not make it the default in ntfs-3g?

Well I can't talk for ntfs-3g developers but here's my guess according to the ntfs-3g manpage:
The ntfs filesystem has no restriction over using the special characters or special filenames itself. However, windows OS puts this restriction for other reasons(take '\' character as an example. That's the character used in paths for dividing dir hierarchy).
So it doesn't seem unreasonable to implement ntfs support in the widest possible manner and make people able to restrict file naming to windows supported names to prevent the consequences I mentioned earlier. It sounds to me somewhat like the option to mount a flashdrive writable or in readonly mode. Both are possible but considering the use cases mounting the flashdrive writable seems more reasonable as a default option.
```
Windows Filename Compatibility
NTFS supports several filename namespaces: DOS, Win32 and POSIX. While the ntfs-3g driver handles all of them, it always creates new files in the POSIX  name‐space  for maximum portability and interoperability reasons. This means that filenames are case sensitive and all characters are allowed except '/' and '\0'. This is perfectly legal on Windows, though some application may get confused. The option windows_names may be used to apply Windows restrictions to  new  file names.

windows_names
This option prevents files, directories and extended attributes to be created with a name not allowed by windows, because
       - it contains some not allowed character,
       - or the last character is a space or a dot,
       - or the name is reserved.
The forbidden characters are the nine characters " * / : < > ? \ | and those whose code is less than 0x20, and the reserved names are  CON,  PRN,  AUX, NUL, COM1..COM9, LPT1..LPT9, with no suffix or followed by a dot.

Existing such files can still be read (and renamed).
```

**Comment by A-Shahbazi** [comment]
> > BTW, I can make a PR if this sounds good to the maintainer.
> 
> Yes, please open a PR with intended changes. Thanks!
> 
> Btw. is this option available in earlier ntfs-3g releases? If not, would it fail mounting or simply gets ignored?

The option has been around since ntfs-3g 2010.8.8 stable version. I don't know of any maintained distro that ships with ntfs-3g implementation older than that.

**Comment by tbzatek** [comment]
Thanks for the exhaustive analysis. Yes, 2010 release is old enough to be considered available in every distribution.

Looking at the source code, we already provide sane mount options that e.g. affect case sensitivity. Traditionally udisks has been targeted for end users with its selection of features and defaults.

**Comment by Bananaman** [comment]
This is a very good change, thank you for doing this.

I just want to mention one more thing: There is one more problem that can affect Windows compatibility.

NTFS itself is case sensitive and supports "duplicate" file/folder names if they have different case, such as "pictures" and "Pictures".

Windows uses a "layer" on top of NTFS which forces everything to be case-insensitive.

So if you create files/folders that only differ by their case, it will work fine in Linux, but as soon as you try to access that location on Windows, you will have massive issues. Windows won't know which file/folder you want to access.

**THERE IS NO FIX FOR THIS IN NTFS-3G.**

They have a very half-assed option named "ignore_case" in the driver, but if you read the manpage for it, that is just a quick and dirty hack, which just makes *all* existing and new files display and save as lowercase. Most likely, they're literally just telling their own internal "filesystem file object" to always read/convert its "name" field as lowercase, which is why it is such a harsh and completely useless option.

Therefore, there is no way to make NTFS-3G's driver behave exactly like Windows (showing case, but not allowing duplicate files of different case).

I am sure they could have done a better job with this feature, but perhaps it's rare enough to not be worth the processing overhead of having to always scan for "same name but different case" anytime the Linux OS requests to access/write a file on NTFS.

So with this being said, every udisks user should keep all of this in mind: Don't mindlessly create duplicate filenames with different case. Always be careful to ensure that all filenames are unique in a case-insensitive world, if Windows compatibility matters to you. And if there is a problem, go back into Linux to fix the duplicate filenames there, since Windows can't rescue you from that situation at all since it can't even access the "shadowed/duplicate" files! :-)

**Comment by Bananaman** [comment]
A clever person came up with a solution for the case sensitivity clashes, by the way.

Just run the following one-liner on Linux to scan all mounted drives case-insensitively. Replace `/mnt` with wherever the disks are, such as `/media` on some distros.

```bash
find /mnt | sort -f | uniq -ic | grep -v '^ *1 ' | sort -n
```

Explanation:

- Find all files and directories.
- Sort case-insensitively.
- Calculate the number of instances per line, case-insensitively. So if there's only one file/dir with a certain name, it'll be prefixed by "1 path", otherwise another number such as "3 path" etc representing how many duplicates there are.
- Discard all lines that start with the number "1" (single instances).
- Sort the duplicates by how many there are of each.

The scanning is very fast on SSDs, even on large system disks with millions of files (a very big Windows OS disk took around 20 seconds for me), and the output will be a list of all duplicates, sorted by how many there are of each.

You simply go to each path and fix it in Linux, if this code discovers any issues.

Due to Google visibility of this ticket, and because it's about Windows compatibility, I think this neat and closed ticket is a decent place to put this information. Good luck to everyone who stumbles on this in the future.

**Comment by tbzatek** [comment]
Thanks for the exhaustive addition, @Bananaman! There's an upcoming Paragon NTFS driver planned to be included in vanilla kernel and there's some hope such issues could be dealt with in a clean way. We'll keep watching the progress as the mount options may be different between these two implementations anyway.

**Comment by Artoria2e5** [comment]
One guy's fix is another guy's breaking change. Case in point: this change breaks Steam Proton on NTFS partitions because it blocks `c:` symlink creation. A symlink that has no practical use in Windows anyways.

https://github.com/ValveSoftware/Proton/issues/5168
