### ISSUE TITLE
Udisk Malware has locked me out of my drives

### ISSUE THREAD

**Issue by Sbarlock12** [storaged-project/udisks#717]
I am not joking. I have been fighting a trojan/malware and now I am locked out of accessing my hard drives without a password. I personally have never heard of you software prior to now.

I click on my drive and this comes up.

"Authentication is required to mount .. (/dev/sda3)
password for root:
details says:
org.freedesktop.udisk2.filesystem-mount-system
Vendor: The Udesk Project

I am not a programmer and want contol of my system back. Please advise. I am running a live version of Linux MX as it is the only thing that will boot my computer.

**Comment by vojtechtrefny** [comment]
In Linux systems with UDisks, you'll be always asked for passphrase when trying to mount a non-removable device, because that is a operation only a privileged user can do (e.g. root/administrator or user with sudo). If you are using Linux MX Live CD your passphrase should be `demo` for the user and `root` for the administrator, see [here](https://www.reddit.com/r/MXLinux/comments/99rg4n/mx_linux_liveusb_administrative_password/).
