### ISSUE TITLE
Udisks2 main process waits for a long time

### ISSUE THREAD

**Issue by HeroesLoveToRoujiamo** [storaged-project/udisks#871]
Two U disks, numbered A and B. Format U Disk A into the EXT3 file system (this process takes a long time). When formatting U Disk A, mount or unmount U Disk B. At this time, the udisks2 main process will update the utab information (utab_changed_event), thereby calling the udisks_linux_filesystem_update() function, and will update the size information of U Disk A. Because U Disk A is being formatted, the main process of udisks2 will freeze (g_spawn_sync) until U Disk A is formatted. The stack when udisks2 freezes is as follows:
![Stack](https://user-images.githubusercontent.com/21233557/113080146-fc95c700-9208-11eb-97e8-aa93950b5cc2.png)

When formatting U Disk A, U Disk A has been uninstalled. At this time, can I not update its utab information?

**Comment by HeroesLoveToRoujiamo** [comment]
I tried to fix this problem, but I don’t seem to be able to merge the code. The link is as follows:
https://github.com/HeroesLoveToRoujiamo/udisks/commit/51ee4d70532e529b869804f190ce81e89e5769d4

**Comment by tbzatek** [comment]
The freeze you're talking about is caused by the actual command being frozen, i.e. `dumpe2fs` in this case. I agree it is rather intrusive.

What we can do here is to try calling the `udisks_linux_block_object_try_lock_for_cleanup()` that was originally intended to prevent the cleanup thread performing any action on a particular block object while any operation is in progress. This might however work only in the case formatting is done through UDisks.
